-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.economics
(
    country_code character(3) COLLATE pg_catalog."default" NOT NULL,
    year integer NOT NULL,
    gdp double precision,
    unemployment_rate real,
    male_unemployment_rate real,
    female_unemployment_rate real,
    poverty_headcount_ratio real,
    literacy_rate double precision,
    electric_power_consumption double precision,
    education_expenditure_ratio double precision,
    current_health_expenditure_ratio double precision,
    current_health_expenditure_per_capita double precision,
    CONSTRAINT economics_pkey PRIMARY KEY (country_code, year)
);

CREATE TABLE IF NOT EXISTS public.population
(
    country_code character(3) COLLATE pg_catalog."default" NOT NULL,
    year integer NOT NULL,
    total_population bigint,
    male_population bigint,
    female_population bigint,
    working_age_population_ratio double precision,
    mortality_rate real,
    life_expectancy real,
    life_expectancy_male real,
    life_expectancy_female real,
    fertility_rate real,
    CONSTRAINT population_pkey PRIMARY KEY (country_code, year)
);

CREATE TABLE IF NOT EXISTS public.regions
(
    country_code character(3) COLLATE pg_catalog."default" NOT NULL,
    name text COLLATE pg_catalog."default",
    region text COLLATE pg_catalog."default",
    "sub-region" text COLLATE pg_catalog."default",
    CONSTRAINT regions_pkey PRIMARY KEY (country_code)
);

ALTER TABLE IF EXISTS public.economics
    ADD CONSTRAINT country_code FOREIGN KEY (country_code)
    REFERENCES public.regions (country_code) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.population
    ADD CONSTRAINT country_code FOREIGN KEY (country_code)
    REFERENCES public.regions (country_code) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;

END;